AWSTemplateFormatVersion: '2010-09-09'
Description: Lex bot using separate intents for persona generation and persona chat

Parameters:
  LexRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /persona/iam/LexRoleArn

  ValidatorLambdaArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /persona/lambda/ValidatorArn

  ChatHandlerLambdaArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /persona/lambda/ChatHandlerArn

Resources:
  PersonaBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Sub "${AWS::StackName}-PersonaGeneratorBot"
      RoleArn: !Ref LexRoleArn
      IdleSessionTTLInSeconds: 300
      DataPrivacy:
        ChildDirected: false
      AutoBuildBotLocales: true
      BotLocales:
        - LocaleId: en_US
          NluConfidenceThreshold: 0.4
          Intents:
            - Name: GeneratePersonaIntent
              SampleUtterances:
                - Create a persona for {CompanyName} with {Characteristics}
                - I want a persona for {CompanyName}
              FulfillmentCodeHook:
                Enabled: true
              Slots:
                - Name: CompanyName
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroups:
                        - Message:
                            PlainTextMessage:
                              Value: What is the company name?
                      MaxRetries: 2
                      AllowInterrupt: true
                - Name: Characteristics
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroups:
                        - Message:
                            PlainTextMessage:
                              Value: What are the company’s characteristics?
                      MaxRetries: 2
                      AllowInterrupt: true
              CodeHook:
                Enabled: true
                LambdaCodeHook:
                  CodeHookInterfaceVersion: "1.0"
                  LambdaArn: !Ref ValidatorLambdaArn

            - Name: ChatWithPersonaIntent
              SampleUtterances:
                - {UserInput}
              FulfillmentCodeHook:
                Enabled: true
              Slots:
                - Name: UserInput
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroups:
                        - Message:
                            PlainTextMessage:
                              Value: What would you like to ask?
                      MaxRetries: 1
                      AllowInterrupt: true
              CodeHook:
                Enabled: true
                LambdaCodeHook:
                  CodeHookInterfaceVersion: "1.0"
                  LambdaArn: !Ref ChatHandlerLambdaArn
