AWSTemplateFormatVersion: '2010-09-09'
Description: Lex V2 Bot with one simple intent

# Parameters:
  # LexServiceRole:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/iam/LexRoleArn
  # ValidatorLambdaARN:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/lambda/ValidatorArn
Resources:
  LexBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: MyPersonaBot
      RoleArn: !Sub '{{resolve:ssm:/persona/iam/LexRoleArn}}'
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      AutoBuildBotLocales: false
      BotLocales:
        - LocaleId: "en_US"
          NluConfidenceThreshold: 0.40
          VoiceSettings:
            VoiceId: Joanna
          SlotTypes:
            - Name: "companyname"
              Description: "Company Name"
              SlotTypeValues:
                - SampleValue:
                    Value: MySweetCompany
                - SampleValue:
                    Value: MyShippingCompany
                - SampleValue:
                    Value: TheBigTransporter
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE
            - Name: "characteristics"
              Description: "Company charestericts"
              SlotTypeValues:
                - SampleValue:
                    Value:  precise control over ingredient ratios, new flavors, product formats,
                - SampleValue:
                    Value: robust logistics network,timely and reliable delivery 
                - SampleValue:
                    Value: fleet of specialized vehicles,continually optimizes routes, manages driver schedules
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE
          Intents:
            - Name: "GetPersonaIntent"
              Description: "Intent to collect company name and charesterticts"
              SampleUtterances:
                - Utterance: "I want to create a persona"
                - Utterance: "Generate a business persona"
                - Utterance: "Hi"
                - Utterance: "Hullo"
              FulfillmentCodeHook:
                Enabled: True
              SlotPriorities:
                - Priority: 2
                  SlotName: characteristics
                - Priority: 1
                  SlotName: companyname
              Slots:
                - Name: "companyname"
                  SlotTypeName: "AMAZON.AlphaNumeric"
                  ValueElicitationSetting: 
                    SlotConstraint: "Required"
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "What is the name of the company"
                      MaxRetries: 3
                      AllowInterrupt: false
                - Name: "characteristics"
                  SlotTypeName: "AMAZON.FreeFormInput"
                  ValueElicitationSetting: 
                    SlotConstraint: "Required"
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "What are the company characteristics"
                      MaxRetries: 3
                      AllowInterrupt: false
            - Name: "FallbackIntent"
              Description: "Default intent when no other intent matches"
              ParentIntentSignature: "AMAZON.FallbackIntent"
              FulfillmentCodeHook:
                Enabled: True

  LexBotBotVersionWithCFN:
    DependsOn: LexBot
    Type: AWS::Lex::BotVersion
    Properties:
      BotId: !Ref LexBot
      BotVersionLocaleSpecification:
        - LocaleId: en_US
          BotVersionLocaleDetails:
            SourceBotVersion: DRAFT
      Description: Version1
  
  LexBotAlias:
    Type: AWS::Lex::BotAlias
    Properties:
      BotId: !Ref LexBot
      BotAliasName: PersonaFinalV
      BotVersion: !GetAtt LexBotBotVersionWithCFN.BotVersion
      SentimentAnalysisSettings:
        DetectSentiment: false
      BotAliasLocaleSettings: 
        - BotAliasLocaleSetting:
            CodeHookSpecification:
              LambdaCodeHook: 
                CodeHookInterfaceVersion: "1.0"
                LambdaArn: !Sub '{{resolve:ssm:/persona/lambda/ValidatorArn}}'
            Enabled: True  
          LocaleId: en_US   
  
  LexBotIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /persona/lex/LexBotID
      Type: String
      Value: !Ref LexBot

  LexBotAliasParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /persona/lex/LexBotAlias
      Type: String
      Value: !Select [0, !Split ["|", !Ref LexBotAlias]]

  LexInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub '{{resolve:ssm:/persona/lambda/ValidatorArn}}'
      Action: lambda:InvokeFunction
      Principal: lex.amazonaws.com
      SourceArn: !GetAtt LexBotAlias.Arn
      # SourceArn: !Sub arn:aws:lex:${AWS::Region}:${AWS::AccountId}:bot-alias/${LexBot}/${LexBotAlias}

Outputs:
  BotId:
    Value: !Ref LexBot
  BotAliasId:
    Value: !Select [0, !Split ["|", !Ref LexBotAlias]]
  BotAliasARN:
    Value: !GetAtt LexBotAlias.Arn
