AWSTemplateFormatVersion: '2010-09-09'
Description: Production-ready Step Function for persona orchestration with guardrails, retries, and logging

Parameters:

  # GuardrailLambdaRoleArn:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/iam/GuardrailLambdaRoleArn

  # LLMLambdaRoleArn:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/iam/LLMLambdaRoleArn
    
  S3Bucket:
      Type: String
      Description: S3 bucket name where Lambda zips are stored
  S3Prefix:
    Type: String
    Description: S3 prefix/folder path where Lambda zips are stored (no trailing slash)

  # StepFunctionExecutionRoleArn:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/iam/StepFunctionExecutionRoleArn
  # GuardrailId:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/bedrock/GuardrailId  
  # GuardrailVersion:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/bedrock/GuardrailVersion
  # LLMModelId:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Default: /persona/bedrock/LLMModelId
Resources:
  GuardrailLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: persona-guardrail-lambda
      Handler: GuardrailLambda.handler
      Role: !Sub '{{resolve:ssm:/persona/iam/GuardrailLambdaRoleArn}}'
      Runtime: nodejs18.x
      Timeout: 10
      Environment:
        Variables:
          GUARDRAIL_ID: !Sub '{{resolve:ssm:/persona/bedrock/GuardrailId}}'
          GUARDRAIL_VERSION: !Sub '{{resolve:ssm:/persona/bedrock/GuardrailVersion}}'
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub "${S3Prefix}/GuardrailLambda.zip"

  LLMLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: persona-llm-lambda
      Handler: LLMLambda.handler
      Role: !Sub '{{resolve:ssm:/persona/iam/LLMLambdaRoleArn}}'
      Runtime: nodejs18.x
      Timeout: 10
      Environment:
        Variables:
          LLM_MODEL_ID: !Sub '{{resolve:ssm:/persona/bedrock/LLMModelId}}'
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub "${S3Prefix}/LLMLambda.zip"
  PersonaStepFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/vendedlogs/states/PersonaOrchestrationLogGroup
      RetentionInDays: 14

  PersonaOrchestrationStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      # StateMachineName: PersonaOrchestration1
      RoleArn: !Sub '{{resolve:ssm:/persona/iam/StepFunctionExecutionRoleArn}}'
      StateMachineType: EXPRESS #For synchronous call
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt PersonaStepFunctionLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
      DefinitionString:
        !Sub |
          {
            "Comment": "Production orchestration for persona generation and chat moderation",
            "StartAt": "GuardrailCheck",
            "States": {
              "GuardrailCheck": {
                "Type": "Task",
                "Resource": "${GuardrailLambda.Arn}",
                "TimeoutSeconds": 10,
                "Retry": [
                  {
                    "ErrorEquals": ["Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException"],
                    "IntervalSeconds": 2,
                    "MaxAttempts": 3,
                    "BackoffRate": 2
                  }
                ],
                "Catch": [
                  {
                    "ErrorEquals": ["States.ALL"],
                    "ResultPath": "$.error",
                    "Next": "BlockedResponse"
                  }
                ],
                "Next": "CallClaude"
              },
              "BlockedResponse": {
                "Type": "Fail",
                "Error": "UnsafeInput",
                "Cause": "Guardrail blocked the input."
              },
              "CallClaude": {
                "Type": "Task",
                "Resource": "${LLMLambda.Arn}",
                "TimeoutSeconds": 20,
                "Retry": [
                  {
                    "ErrorEquals": ["Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException"],
                    "IntervalSeconds": 2,
                    "MaxAttempts": 2,
                    "BackoffRate": 2
                  }
                ],
                "Catch": [
                  {
                    "ErrorEquals": ["States.ALL"],
                    "ResultPath": "$.error",
                    "Next": "ClaudeFailure"
                  }
                ],
                "End": true
              },
              "ClaudeFailure": {
                "Type": "Fail",
                "Error": "ClaudeError",
                "Cause": "Claude failed after retries"
              }
            }
          }

  PersonaStepFunctionArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /persona/stepfunction/PersonaOrchestrationArn
      Type: String
      Value: !Ref PersonaOrchestrationStepFunction

  GuardrailLambdaParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /persona/lambda/GuardrailArn
      Type: String
      Value: !GetAtt GuardrailLambda.Arn

  LLMLambdaParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /persona/lambda/LLMLambdaArn
      Type: String
      Value: !GetAtt LLMLambda.Arn
